export const PROMPTS: string[] = [
  "The worst way to start a Monday _____",
  "My reaction when the WiFi goes down _____",
  "What my boss thinks I do vs. what I actually do _____",
  "Nobody told me adulting would include _____",
  "The face I make when someone says 'quick question' _____",
  "Me at 2am after one more episode _____",
  "When the self-checkout machine says 'unexpected item' _____",
  "My spirit animal is _____",
  "What 5 more minutes of sleep looks like _____",
  "The energy I bring to Mondays _____",
  "Explaining my search history to my future self _____",
  "When someone cancels plans I didn't want to go to anyway _____",
  "Me pretending to know what's happening in the meeting _____",
  "The noise I make stepping on a Lego _____",
  "Opening the fridge for the 5th time hoping something new appeared _____",
  "My cardio routine _____",
  "When the group chat finally goes quiet _____",
  "That moment when the song you forgot existed comes on _____",
  "How I look typing a strongly worded email _____",
  "Trying to act natural after tripping in public _____",
  "My entire personality at a buffet _____",
  "When autocorrect sends something and you just let it go _____",
  "A surprise party thrown in my honor _____",
  "What happens when I say 'I'll just have one drink' _____",
  "Pretending to be busy when someone walks past my desk _____",
  "My relationship with deadlines _____",
  "When the plot twist hits in a show you've been half-watching _____",
  "The dance I do when nobody's looking _____",
  "My reaction to 'we need to talk' _____",
  "Trying to remember why I walked into a room _____",
  "When the pizza arrives exactly on time _____",
  "My body at 8pm after doing nothing all day _____",
  "The energy of a 7am meeting on a Friday _____",
  "When someone asks if I'm okay and I say 'I'm fine' _____",
  "Me explaining why I need 12 browser tabs open _____",
  "The vibe I send when someone chews loudly near me _____",
  "That feeling when you nail parallel parking on the first try _____",
  "When the store says they're out of your one item _____",
  "My cooking process vs. the recipe _____",
  "How I look doing anything athletic _____",
  "When I finally finish a series and don't know what to do with my life _____",
  "What 'eating healthy this week' looks like by Thursday _____",
  "Me silently judging the movie choices at a sleepover _____",
  "When someone spoils a show I've been avoiding _____",
  "The noise my knees make going up stairs _____",
  "Me acting like I remember your name _____",
  "When a baby or dog gets more attention than me _____",
  "My face during a 'quick 30-minute' call that hits hour two _____",
  "What 'we'll leave in 5 minutes' actually means _____",
  "The look I give my bank account after a weekend _____",
  "Me trying to act cool when I see a celebrity _____",
  "How I handle spicy food to impress someone _____",
  "When the vending machine takes my dollar but doesn't drop the snack _____",
  "My morning routine before coffee _____",
  "What it looks like when I say 'I'm almost ready' _____",
  "Me trying to remember where I put my phone (while holding my phone) _____",
  "When I'm third-wheeling but pretending I'm not _____",
  "That face when someone asks me to be in a photo I didn't consent to _____",
  "The energy of trying to return something without a receipt _____",
  "My internal reaction when I get a 'can I ask you something?' text _____",
  "When the elevator door starts closing and you make eye contact with someone running for it _____",
  "How I handle being voluntold to do something _____",
  "Me acting normal while waiting for someone to notice my haircut _____",
  "The energy I give off at a party I didn't really want to attend _____",
  "When someone else orders what I was going to order _____",
  "My face when the bill arrives and I didn't realize how expensive it was _____",
  "Walking away after a really good comeback _____",
  "What happens when I try to whisper _____",
  "The chaos of being late and trying to act casual _____",
  "My negotiation tactics when arguing with myself about a late-night snack _____",
  "When a movie I thought would be bad turns out to be incredible _____",
  "Me vs. the jar that will not open _____",
  "My confidence level ordering food in a foreign language _____",
  "What running to catch public transit looks like _____",
  "The feeling when you wake up and realize it's Saturday _____",
  "Me when a stranger laughs at my joke _____",
  "How I handle being asked to 'say a few words' without warning _____",
  "When someone on the phone says 'one moment please' for 20 minutes _____",
  "My reaction when the trailer was better than the actual movie _____",
  "That feeling when you finally find a comfortable position in bed _____",
  "Me explaining why I need yet another streaming subscription _____",
  "How I look 'casually' eavesdropping _____",
  "When the group project is due and I realize I'm the only one who did anything _____",
  "My coping mechanism when plans change last minute _____",
  "What 'I'll start tomorrow' energy looks like _____",
  "When someone turns on the overhead light in a dark room _____",
  "Me trying to open a bag of chips quietly in a silent room _____",
  "The face I make reading terms and conditions before clicking Accept _____",
  "When my phone predicts exactly what I was about to type _____",
  "My level of focus 10 minutes before the end of a workday _____",
  "What 'just browsing' at a store turns into _____",
  "When the vibe at a party matches exactly what I needed _____",
  "Me catching myself talking to my pet like they understand _____",
  "That moment when the song switches to the part you've been waiting for _____",
  "How I handle slow walkers on a sidewalk _____",
  "My face the moment I send a message to the wrong person _____",
  "When someone asks what I want for my birthday and I go blank _____",
  "Me explaining how I spent an entire Saturday doing 'nothing' _____",
  "What studying for 10 minutes and then taking a 2-hour break looks like _____",
  "My energy being the last one awake at a sleepover _____",
  "When someone says 'this won't take long' and then it absolutely does _____",
  "The face I make trying to read the handwriting of a doctor's note _____",
  "How I handle running into someone I definitely saw but pretended not to _____",
  "Me completing one task on my to-do list and acting like the day was productive _____",
  "When I realize I've been on my phone for two hours and gained nothing _____",
  "My spirit leaving my body during a particularly bad team-building exercise _____",
  "The energy of seeing a 'loading' spinner at a crucial moment _____",
  "Me trying to look unbothered when I'm very, very bothered _____",
  "What happens when I say 'I don't care what we eat' and then veto every suggestion _____",
  "When someone in the group chat leaves you on read after your best message _____",
  "My reaction when I realize I've been mispronouncing a word for years _____",
  "How I approach something I promised myself I'd do months ago _____",
  "The face I make trying to fit a large item into a small trunk _____",
  "Me trying to act like I remember meeting someone for the third time _____",
  "What 'I'll just rest my eyes for a second' turns into _____",
  "When someone says 'I have a fun icebreaker game for us all' _____",
  "My strategy for avoiding someone in a grocery store _____",
  "The moment I realize I left my headphones at home _____",
  "Me acting like I wasn't just talking about them before they walked in _____",
  "What a 'productive' Sunday looks like vs. what it actually looks like _____",
  "When the traffic finally clears after sitting for 30 minutes for no reason _____",
  "My internal monologue untangling headphones _____",
  "When a stranger is friendlier than I expected and I'm not ready for it _____",
  "Me trying to parallel park with people watching _____",
  "That one teammate who says 'can we circle back?' in every meeting _____",
  "What I look like trying to catch something I knocked off a counter _____",
  "How I react to automated customer service phone trees _____",
  "When someone says 'trust me, you'll love it' about food I definitely won't love _____",
  "Me the moment I realize I set my alarm for PM instead of AM _____",
  "The energy of a chat notification sound during a really quiet moment _____",
  "When something 'five minutes away' is clearly not five minutes away _____",
  "My inner child seeing the dessert menu _____",
  "What 'let's keep this meeting short' actually means _____",
  "When the last episode of a season ends on a cliffhanger and the next one isn't out yet _____",
  "Me watching someone pack a suitcase 'efficiently' when I know it won't close _____",
  "My face during a conversation when I have absolutely nothing to add _____",
  "When I find $20 in an old jacket pocket _____",
  "How I explain to someone why I know so much random trivia _____",
  "Me when the song I requested finally comes on _____",
  "What happens when I try to multitask _____",
  "The energy of realizing autocomplete just sent a draft message _____",
  "When someone says 'this is a safe space to share' in a work context _____",
  "My negotiation with myself about whether a thing counts as clean _____",
  "What 'getting dressed up' versus 'casual' means to me specifically _____",
  "Me watching my train or bus pull away as I reach the platform _____",
  "When someone interrupts a story right before the good part _____",
  "What 'it's fine, I'm not upset' actually looks like on my face _____",
  "My general attitude toward anything that requires assembly _____",
  "When the only open checkout lane has the world's most complicated transaction ahead of me _____",
  "My performance having a 'relaxed conversation' when I actually care a lot _____",
  "What I'm doing at 3am that I definitely shouldn't be doing _____",
  "When I nail a presentation and walk out of the room _____",
  "The energy of the last 15 minutes before a long weekend _____",
  "What happens in my brain the moment I lie down and remember everything I forgot to do _____",
  "My face when someone finds a loophole in a game I was winning _____",
  "When someone in the group says 'I'm not really a dessert person' _____",
  "Me every time I say I'm going to bed early _____",
];
