export const PROMPTS: string[] = [
  "The worst way to start a Monday.",
  "My reaction when the WiFi goes down.",
  "What my boss thinks I do vs. what I actually do.",
  "Nobody told me adulting would include.",
  "The face I make when someone says 'quick question'.",
  "Me at 2am after one more episode.",
  "When the self-checkout machine says 'unexpected item'.",
  "My spirit animal is.",
  "What 5 more minutes of sleep looks like.",
  "The energy I bring to Mondays.",
  "Explaining my search history to my future self.",
  "When someone cancels plans I didn't want to go to anyway.",
  "Me pretending to know what's happening in the meeting.",
  "The noise I make stepping on a Lego.",
  "Opening the fridge for the 5th time hoping something new appeared.",
  "My cardio routine.",
  "When the group chat finally goes quiet.",
  "That moment when the song you forgot existed comes on.",
  "How I look typing a strongly worded email.",
  "Trying to act natural after tripping in public.",
  "My entire personality at a buffet.",
  "When autocorrect sends something and you just let it go.",
  "A surprise party thrown in my honor.",
  "What happens when I say 'I'll just have one drink'.",
  "Pretending to be busy when someone walks past my desk.",
  "My relationship with deadlines.",
  "When the plot twist hits in a show you've been half-watching.",
  "The dance I do when nobody's looking.",
  "My reaction to 'we need to talk'.",
  "Trying to remember why I walked into a room.",
  "When the pizza arrives exactly on time.",
  "My body at 8pm after doing nothing all day.",
  "The energy of a 7am meeting on a Friday.",
  "When someone asks if I'm okay and I say 'I'm fine'.",
  "Me explaining why I need 12 browser tabs open.",
  "The vibe I send when someone chews loudly near me.",
  "That feeling when you nail parallel parking on the first try.",
  "When the store says they're out of your one item.",
  "My cooking process vs. the recipe.",
  "How I look doing anything athletic.",
  "When I finally finish a series and don't know what to do with my life.",
  "What 'eating healthy this week' looks like by Thursday.",
  "Me silently judging the movie choices at a sleepover.",
  "When someone spoils a show I've been avoiding.",
  "The noise my knees make going up stairs.",
  "Me acting like I remember your name.",
  "When a baby or dog gets more attention than me.",
  "My face during a 'quick 30-minute' call that hits hour two.",
  "What 'we'll leave in 5 minutes' actually means.",
  "The look I give my bank account after a weekend.",
  "Me trying to act cool when I see a celebrity.",
  "How I handle spicy food to impress someone.",
  "When the vending machine takes my dollar but doesn't drop the snack.",
  "My morning routine before coffee.",
  "What it looks like when I say 'I'm almost ready'.",
  "Me trying to remember where I put my phone (while holding my phone).",
  "When I'm third-wheeling but pretending I'm not.",
  "That face when someone asks me to be in a photo I didn't consent to.",
  "The energy of trying to return something without a receipt.",
  "My internal reaction when I get a 'can I ask you something?' text.",
  "When the elevator door starts closing and you make eye contact with someone running for it.",
  "How I handle being voluntold to do something.",
  "Me acting normal while waiting for someone to notice my haircut.",
  "The energy I give off at a party I didn't really want to attend.",
  "When someone else orders what I was going to order.",
  "My face when the bill arrives and I didn't realize how expensive it was.",
  "Walking away after a really good comeback.",
  "What happens when I try to whisper.",
  "The chaos of being late and trying to act casual.",
  "My negotiation tactics when arguing with myself about a late-night snack.",
  "When a movie I thought would be bad turns out to be incredible.",
  "Me vs. the jar that will not open.",
  "My confidence level ordering food in a foreign language.",
  "What running to catch public transit looks like.",
  "The feeling when you wake up and realize it's Saturday.",
  "Me when a stranger laughs at my joke.",
  "How I handle being asked to 'say a few words' without warning.",
  "When someone on the phone says 'one moment please' for 20 minutes.",
  "My reaction when the trailer was better than the actual movie.",
  "That feeling when you finally find a comfortable position in bed.",
  "Me explaining why I need yet another streaming subscription.",
  "How I look 'casually' eavesdropping.",
  "When the group project is due and I realize I'm the only one who did anything.",
  "My coping mechanism when plans change last minute.",
  "What 'I'll start tomorrow' energy looks like.",
  "When someone turns on the overhead light in a dark room.",
  "Me trying to open a bag of chips quietly in a silent room.",
  "The face I make reading terms and conditions before clicking Accept.",
  "When my phone predicts exactly what I was about to type.",
  "My level of focus 10 minutes before the end of a workday.",
  "What 'just browsing' at a store turns into.",
  "When the vibe at a party matches exactly what I needed.",
  "Me catching myself talking to my pet like they understand.",
  "That moment when the song switches to the part you've been waiting for.",
  "How I handle slow walkers on a sidewalk.",
  "My face the moment I send a message to the wrong person.",
  "When someone asks what I want for my birthday and I go blank.",
  "Me explaining how I spent an entire Saturday doing 'nothing'.",
  "What studying for 10 minutes and then taking a 2-hour break looks like.",
  "My energy being the last one awake at a sleepover.",
  "When someone says 'this won't take long' and then it absolutely does.",
  "The face I make trying to read the handwriting of a doctor's note.",
  "How I handle running into someone I definitely saw but pretended not to.",
  "Me completing one task on my to-do list and acting like the day was productive.",
  "When I realize I've been on my phone for two hours and gained nothing.",
  "My spirit leaving my body during a particularly bad team-building exercise.",
  "The energy of seeing a 'loading' spinner at a crucial moment.",
  "Me trying to look unbothered when I'm very, very bothered.",
  "What happens when I say 'I don't care what we eat' and then veto every suggestion.",
  "When someone in the group chat leaves you on read after your best message.",
  "My reaction when I realize I've been mispronouncing a word for years.",
  "How I approach something I promised myself I'd do months ago.",
  "The face I make trying to fit a large item into a small trunk.",
  "Me trying to act like I remember meeting someone for the third time.",
  "What 'I'll just rest my eyes for a second' turns into.",
  "When someone says 'I have a fun icebreaker game for us all'.",
  "My strategy for avoiding someone in a grocery store.",
  "The moment I realize I left my headphones at home.",
  "Me acting like I wasn't just talking about them before they walked in.",
  "What a 'productive' Sunday looks like vs. what it actually looks like.",
  "When the traffic finally clears after sitting for 30 minutes for no reason.",
  "My internal monologue untangling headphones.",
  "When a stranger is friendlier than I expected and I'm not ready for it.",
  "Me trying to parallel park with people watching.",
  "That one teammate who says 'can we circle back?' in every meeting.",
  "What I look like trying to catch something I knocked off a counter.",
  "How I react to automated customer service phone trees.",
  "When someone says 'trust me, you'll love it' about food I definitely won't love.",
  "Me the moment I realize I set my alarm for PM instead of AM.",
  "The energy of a chat notification sound during a really quiet moment.",
  "When something 'five minutes away' is clearly not five minutes away.",
  "My inner child seeing the dessert menu.",
  "What 'let's keep this meeting short' actually means.",
  "When the last episode of a season ends on a cliffhanger and the next one isn't out yet.",
  "Me watching someone pack a suitcase 'efficiently' when I know it won't close.",
  "My face during a conversation when I have absolutely nothing to add.",
  "When I find $20 in an old jacket pocket.",
  "How I explain to someone why I know so much random trivia.",
  "Me when the song I requested finally comes on.",
  "What happens when I try to multitask.",
  "The energy of realizing autocomplete just sent a draft message.",
  "When someone says 'this is a safe space to share' in a work context.",
  "My negotiation with myself about whether a thing counts as clean.",
  "What 'getting dressed up' versus 'casual' means to me specifically.",
  "Me watching my train or bus pull away as I reach the platform.",
  "When someone interrupts a story right before the good part.",
  "What 'it's fine, I'm not upset' actually looks like on my face.",
  "My general attitude toward anything that requires assembly.",
  "When the only open checkout lane has the world's most complicated transaction ahead of me.",
  "My performance having a 'relaxed conversation' when I actually care a lot.",
  "What I'm doing at 3am that I definitely shouldn't be doing.",
  "When I nail a presentation and walk out of the room.",
  "The energy of the last 15 minutes before a long weekend.",
  "What happens in my brain the moment I lie down and remember everything I forgot to do.",
  "My face when someone finds a loophole in a game I was winning.",
  "When someone in the group says 'I'm not really a dessert person'.",
  "Me every time I say I'm going to bed early.",
];
